name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd packages/compiler && npm ci
        cd ../runtime && npm ci  
        cd ../cli && npm ci
    
    - name: Build packages
      run: |
        cd packages/compiler && npm run build
        cd ../runtime && npm run build
        cd ../cli && npm run build
    
    - name: Run tests
      run: |
        cd packages/compiler && npm test || echo "Tests not implemented yet"
        cd ../runtime && npm test || echo "Tests not implemented yet"
    
    - name: Test CLI functionality
      run: |
        cd packages/cli
        echo 'strategy TestStrategy { }' > test.crowe
        node dist/index.js compile test.crowe
        rm test.crowe
